project:
  type: website
  output-dir: docs
  
website:
  title: "Hazel Gordon"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - cv.qmd
      - projects.qmd
    tools:
      - icon: github
        href: https://github.com/hazelcgordon/cv
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Hazel Gordon"

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    toc: false

editor: source

