---
title: ""
---

<strong></strong>
<em></em>
<br>

<h2>Education</h2>

<p class="center-text"><strong>PhD in Political Psychology</strong><br>University of Sheffield, October 2022 - Present<br>Economic and Social Research Council, White Rose DTP (Civil Society, Development and Democracy pathway)</p>

<p class="center-text"><strong>MA Social Research, Distinction</strong><br>University of Sheffield, October 2021 – September 2022</p>

<p class="center-text"><strong>MSc Psychology of Education (BPS), Distinction</strong><br>University of Bristol, October 2018 – September 2019</p>

<p class="center-text"><strong>BA Combined Honours, Psychology and Philosophy, First Class Honours</strong><br>University of Newcastle, October 2015 – June 2018</p>

<h2>Research Experience</h2>

<p class="center-text"><strong>Research and Policy Team Placement</strong><br>Electoral Reform Society, May 2024 - July 2024</p>

- Worked with the team to provide timely data analysis, disseminated in a format to inform the public during the 2024 GE election period.
- Created an information hub through github pages to analyse data released by the Electoral Commission on donations made to political parties during the build up to the 2024 GE.
- Wrote blog posts to make my research and the wider research of the organisation easily consumable by a non-specialist audience.
- Presented on the Psychology of trust and how recent research can be harnessed for the purposes of the organisation.

<p class="center-text"><strong>Research Assistant in Political Psychology, Part Time</strong><br>University of Sheffield, September 2019 - September 2021</p>

<p>An ESRC funded research project investigating how political satire, such as memes and satirical television shows, influenced political perceptions. As a key tool of political communication, particularly in the internet age, this project used a mixed methods approach to explore if individuals with opposing political views reacted differently to different types of humorous messaging, and asked how this could shape 'echo chamber' online environments. In my role as a research assistant:</p>

- I acted as a mediator or assistant to the mediator across 13 focus groups.
- I worked regularly within an inter-disciplinary research team to develop the experimental methodology and interpret the meaning and wider significance of the findings.
- I sourced and recruited professional comedians to develop bespoke satirical material for our research, managing communications between candidates and the team during the hiring process.
- I developed ways to increase the validity of methodological decisions, for example by creating a coding system for experimental materials to check those used in the study targeted opposing ideologies with equal breadth, ensuring experimental conditions were comparable.
- I contributed to manuscript development and made suggestions for structural revisions to communicate the research with more clarity.

<h2>Conference Presentations</h2>

<h2>Development of Skills</h2>

<h3>Communication: Written</h3>

<h3>Communication: Verbal</h3>

<h3>Problem Solving</h3>

<h3>Collaboration</h3>

<h3>Statistics</h3>

  


